### ISSUE TITLE
Update in mockup

### ISSUE THREAD

**Issue by bhnauj** [alerayes/nexum#2]
We need to reduce few functionality as it is of no use

- Global search bar
- Remove job categories from left bar
- Remove copy link button
<img width="545" alt="Screen Shot 2022-10-20 at 5 54 06 PM" src="https://user-images.githubusercontent.com/38237550/197086544-625a1d90-bfea-4679-a8d2-1191c3d077ea.png">

**Comment by gurjotsinghdev** [comment]
Hello @bhnauj! Thankyou for reporting this issue. I will take this issue to the design team to discuss further.

**Comment by massi00** [comment]
@bhnauj Please check the mockup as these issues have been resolved in it. Thanks!

**Comment by gurjotsinghdev** [comment]
I am marking this issue closed now. If there are any more concerns, please create a new issue.
